version: '3'
services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8001:8001'
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    ports:
      - '3306:3306'
    environment:
      - MYSQL_DATABASE=doctorai
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./data.sql:/docker-entrypoint-initdb.d/data.sql
      - ./data2.sql:/docker-entrypoint-initdb.d/data2.sql
